version: "3.9"
services:
  orchestrator:
    build:
      context: ..
      dockerfile: infra/docker/Dockerfile.orchestrator
    ports:
      - "8000:8000"
  ui:
    build:
      context: ..
      dockerfile: infra/docker/Dockerfile.ui
    ports:
      - "8501:8501"
    depends_on:
      - orchestrator
